#############################################################################
# Makefile for building: mt0.app/Contents/MacOS/mt0
# Generated by qmake (3.1) (Qt 5.12.9)
# Project:  mt0.pro
# Template: app
# Command: /opt/local/qt5/qtbase/bin/qmake -o Makefile mt0.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I. -I/opt/local/qt5/qtbase/include -I/opt/local/qt5/qtbase/include/QtWidgets -I/opt/local/qt5/qtbase/include/QtGui -I/opt/local/qt5/qtbase/include/QtCore -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I/opt/local/qt5/qtbase/mkspecs/macx-clang -F/opt/local/qt5/qtbase/lib
QMAKE         = /opt/local/qt5/qtbase/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /opt/local/qt5/qtbase/bin/qmake -install qinstall
QINSTALL_PROGRAM = /opt/local/qt5/qtbase/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = mt01.0.0
DISTDIR = /Users/ursl/pi/qt/mt0/.tmp/mt01.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/opt/local/qt5/qtbase/lib
LIBS          = $(SUBLIBS) -F/opt/local/qt5/qtbase/lib -framework QtWidgets -framework QtGui -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cc \
		dialog.cc \
		drivehardware.cc moc_dialog.cpp
OBJECTS       = main.o \
		dialog.o \
		drivehardware.o \
		moc_dialog.o
DIST          = /opt/local/qt5/qtbase/mkspecs/features/spec_pre.prf \
		/opt/local/qt5/qtbase/mkspecs/qdevice.pri \
		/opt/local/qt5/qtbase/mkspecs/features/device_config.prf \
		/opt/local/qt5/qtbase/mkspecs/common/unix.conf \
		/opt/local/qt5/qtbase/mkspecs/common/mac.conf \
		/opt/local/qt5/qtbase/mkspecs/common/macx.conf \
		/opt/local/qt5/qtbase/mkspecs/common/sanitize.conf \
		/opt/local/qt5/qtbase/mkspecs/common/gcc-base.conf \
		/opt/local/qt5/qtbase/mkspecs/common/gcc-base-mac.conf \
		/opt/local/qt5/qtbase/mkspecs/common/clang.conf \
		/opt/local/qt5/qtbase/mkspecs/common/clang-mac.conf \
		/opt/local/qt5/qtbase/mkspecs/qconfig.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_clip2tri.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_clipper.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_openwnn.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_pinyin.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_poly2tri.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_tcime.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3drender.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_charts.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_core.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_help.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_location.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_location_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_network.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_repparser.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_script.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scxml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webengine.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webview.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_canbusutil.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qgltf.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmljs.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmllint.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlscene.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qvkgen.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qwebengine_convert_dict.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_repc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_uic.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		/opt/local/qt5/qtbase/mkspecs/features/qt_functions.prf \
		/opt/local/qt5/qtbase/mkspecs/features/qt_config.prf \
		/opt/local/qt5/qtbase/mkspecs/macx-clang/qmake.conf \
		/opt/local/qt5/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/qt5/qtbase/mkspecs/features/exclusive_builds.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/sdk.prf \
		/opt/local/qt5/qtbase/mkspecs/features/toolchain.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/toolchain.prf \
		/opt/local/qt5/qtbase/mkspecs/features/default_pre.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/default_pre.prf \
		/opt/local/qt5/qtbase/mkspecs/features/resolve_config.prf \
		/opt/local/qt5/qtbase/mkspecs/features/default_post.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/default_post.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/objective_c.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/mac.prf \
		/opt/local/qt5/qtbase/mkspecs/features/warn_on.prf \
		/opt/local/qt5/qtbase/mkspecs/features/qt.prf \
		/opt/local/qt5/qtbase/mkspecs/features/resources.prf \
		/opt/local/qt5/qtbase/mkspecs/features/moc.prf \
		/opt/local/qt5/qtbase/mkspecs/features/unix/opengl.prf \
		/opt/local/qt5/qtbase/mkspecs/features/uic.prf \
		/opt/local/qt5/qtbase/mkspecs/features/unix/thread.prf \
		/opt/local/qt5/qtbase/mkspecs/features/qmake_use.prf \
		/opt/local/qt5/qtbase/mkspecs/features/file_copies.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/rez.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/asset_catalogs.prf \
		/opt/local/qt5/qtbase/mkspecs/features/testcase_targets.prf \
		/opt/local/qt5/qtbase/mkspecs/features/exceptions.prf \
		/opt/local/qt5/qtbase/mkspecs/features/yacc.prf \
		/opt/local/qt5/qtbase/mkspecs/features/lex.prf \
		mt0.pro dialog.hh \
		driveHardware.hh main.cc \
		dialog.cc \
		drivehardware.cc
QMAKE_TARGET  = mt0
DESTDIR       = 
TARGET        = mt0.app/Contents/MacOS/mt0

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15.4
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/ursl/pi/qt/mt0/mt0.pro


include /opt/local/qt5/qtbase/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

mt0.app/Contents/MacOS/mt0: ui_dialog.h $(OBJECTS)  
	@test -d mt0.app/Contents/MacOS/ || mkdir -p mt0.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: mt0.pro /opt/local/qt5/qtbase/mkspecs/macx-clang/qmake.conf /opt/local/qt5/qtbase/mkspecs/features/spec_pre.prf \
		/opt/local/qt5/qtbase/mkspecs/qdevice.pri \
		/opt/local/qt5/qtbase/mkspecs/features/device_config.prf \
		/opt/local/qt5/qtbase/mkspecs/common/unix.conf \
		/opt/local/qt5/qtbase/mkspecs/common/mac.conf \
		/opt/local/qt5/qtbase/mkspecs/common/macx.conf \
		/opt/local/qt5/qtbase/mkspecs/common/sanitize.conf \
		/opt/local/qt5/qtbase/mkspecs/common/gcc-base.conf \
		/opt/local/qt5/qtbase/mkspecs/common/gcc-base-mac.conf \
		/opt/local/qt5/qtbase/mkspecs/common/clang.conf \
		/opt/local/qt5/qtbase/mkspecs/common/clang-mac.conf \
		/opt/local/qt5/qtbase/mkspecs/qconfig.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_clip2tri.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_clipper.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_openwnn.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_pcre2.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_pinyin.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_poly2tri.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_tcime.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3danimation.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dextras.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3drender.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_charts.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_charts_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_core.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_datavisualization.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_dbus.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designer.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gamepad.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gui.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_help.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_location.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_location_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_network.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_networkauth.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioningquick.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_purchasing.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quick.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_repparser.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_repparser_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_script.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scxml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scxml_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialbus.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sql.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_svg.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_texttospeech.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webengine.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webengine_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecore.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_websockets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webview.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webview_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_canbusutil.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdoc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qgltf.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qlalr.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qml.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmljs.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmllint.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlscene.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qvkgen.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qwebengine_convert_dict.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_repc.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_uic.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri \
		/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri \
		/opt/local/qt5/qtbase/mkspecs/features/qt_functions.prf \
		/opt/local/qt5/qtbase/mkspecs/features/qt_config.prf \
		/opt/local/qt5/qtbase/mkspecs/macx-clang/qmake.conf \
		/opt/local/qt5/qtbase/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/local/qt5/qtbase/mkspecs/features/exclusive_builds.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/sdk.prf \
		/opt/local/qt5/qtbase/mkspecs/features/toolchain.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/toolchain.prf \
		/opt/local/qt5/qtbase/mkspecs/features/default_pre.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/default_pre.prf \
		/opt/local/qt5/qtbase/mkspecs/features/resolve_config.prf \
		/opt/local/qt5/qtbase/mkspecs/features/default_post.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/default_post.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/objective_c.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/mac.prf \
		/opt/local/qt5/qtbase/mkspecs/features/warn_on.prf \
		/opt/local/qt5/qtbase/mkspecs/features/qt.prf \
		/opt/local/qt5/qtbase/mkspecs/features/resources.prf \
		/opt/local/qt5/qtbase/mkspecs/features/moc.prf \
		/opt/local/qt5/qtbase/mkspecs/features/unix/opengl.prf \
		/opt/local/qt5/qtbase/mkspecs/features/uic.prf \
		/opt/local/qt5/qtbase/mkspecs/features/unix/thread.prf \
		/opt/local/qt5/qtbase/mkspecs/features/qmake_use.prf \
		/opt/local/qt5/qtbase/mkspecs/features/file_copies.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/rez.prf \
		/opt/local/qt5/qtbase/mkspecs/features/mac/asset_catalogs.prf \
		/opt/local/qt5/qtbase/mkspecs/features/testcase_targets.prf \
		/opt/local/qt5/qtbase/mkspecs/features/exceptions.prf \
		/opt/local/qt5/qtbase/mkspecs/features/yacc.prf \
		/opt/local/qt5/qtbase/mkspecs/features/lex.prf \
		mt0.pro \
		/opt/local/qt5/qtbase/lib/QtWidgets.framework/QtWidgets.prl \
		/opt/local/qt5/qtbase/lib/QtGui.framework/QtGui.prl \
		/opt/local/qt5/qtbase/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile mt0.pro
/opt/local/qt5/qtbase/mkspecs/features/spec_pre.prf:
/opt/local/qt5/qtbase/mkspecs/qdevice.pri:
/opt/local/qt5/qtbase/mkspecs/features/device_config.prf:
/opt/local/qt5/qtbase/mkspecs/common/unix.conf:
/opt/local/qt5/qtbase/mkspecs/common/mac.conf:
/opt/local/qt5/qtbase/mkspecs/common/macx.conf:
/opt/local/qt5/qtbase/mkspecs/common/sanitize.conf:
/opt/local/qt5/qtbase/mkspecs/common/gcc-base.conf:
/opt/local/qt5/qtbase/mkspecs/common/gcc-base-mac.conf:
/opt/local/qt5/qtbase/mkspecs/common/clang.conf:
/opt/local/qt5/qtbase/mkspecs/common/clang-mac.conf:
/opt/local/qt5/qtbase/mkspecs/qconfig.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_clip2tri.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_clipper.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_harfbuzz.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_openwnn.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_pcre2.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_pinyin.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_poly2tri.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_qmapboxgl.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_ext_tcime.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3danimation.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3danimation_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dcore.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dextras.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dextras_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dinput.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquick.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickextras_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3drender.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_dbus_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_charts.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_charts_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_clipboard_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_concurrent.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_core.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_core_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_datavisualization.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_datavisualization_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_dbus.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designer.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designer_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_designercomponents_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_edid_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gamepad.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gamepad_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_graphics_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gui.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_gui_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_help.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_help_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_location.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_location_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_macextras.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_macextras_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimedia.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_network.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_network_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_networkauth.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_networkauth_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_nfc.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_opengl.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioning.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioningquick.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_positioningquick_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_printsupport.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_purchasing.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_purchasing_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qml.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qml_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmldebug_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmltest.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quick.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quick_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickshapes_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_remoteobjects_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_repparser.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_repparser_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_script.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_script_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scripttools.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scxml.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_scxml_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sensors.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialbus.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialbus_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialport.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sql.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_sql_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_svg.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_svg_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_testlib.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_texttospeech.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_texttospeech_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uitools.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webchannel.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webengine.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webengine_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecore.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecore_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginewidgets.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_websockets.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webview.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_webview_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_widgets.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xml.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xml_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_canbusutil.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lconvert.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lrelease.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_lupdate.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qcollectiongenerator.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdbuscpp2xml.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdbusxml2cpp.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qdoc.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qgltf.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qhelpgenerator.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qlalr.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qml.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlcachegen.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlimportscanner.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmljs.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmllint.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlmin.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlplugindump.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlpreview.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlprofiler.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmlscene.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qmltestrunner.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qscxmlc.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qtattributionsscanner.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qvkgen.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_qwebengine_convert_dict.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_repc.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_uic.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatterns.pri:
/opt/local/qt5/qtbase/mkspecs/modules/qt_tool_xmlpatternsvalidator.pri:
/opt/local/qt5/qtbase/mkspecs/features/qt_functions.prf:
/opt/local/qt5/qtbase/mkspecs/features/qt_config.prf:
/opt/local/qt5/qtbase/mkspecs/macx-clang/qmake.conf:
/opt/local/qt5/qtbase/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/local/qt5/qtbase/mkspecs/features/exclusive_builds.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/sdk.prf:
/opt/local/qt5/qtbase/mkspecs/features/toolchain.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/toolchain.prf:
/opt/local/qt5/qtbase/mkspecs/features/default_pre.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/default_pre.prf:
/opt/local/qt5/qtbase/mkspecs/features/resolve_config.prf:
/opt/local/qt5/qtbase/mkspecs/features/default_post.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/default_post.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/objective_c.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/mac.prf:
/opt/local/qt5/qtbase/mkspecs/features/warn_on.prf:
/opt/local/qt5/qtbase/mkspecs/features/qt.prf:
/opt/local/qt5/qtbase/mkspecs/features/resources.prf:
/opt/local/qt5/qtbase/mkspecs/features/moc.prf:
/opt/local/qt5/qtbase/mkspecs/features/unix/opengl.prf:
/opt/local/qt5/qtbase/mkspecs/features/uic.prf:
/opt/local/qt5/qtbase/mkspecs/features/unix/thread.prf:
/opt/local/qt5/qtbase/mkspecs/features/qmake_use.prf:
/opt/local/qt5/qtbase/mkspecs/features/file_copies.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/rez.prf:
/opt/local/qt5/qtbase/mkspecs/features/mac/asset_catalogs.prf:
/opt/local/qt5/qtbase/mkspecs/features/testcase_targets.prf:
/opt/local/qt5/qtbase/mkspecs/features/exceptions.prf:
/opt/local/qt5/qtbase/mkspecs/features/yacc.prf:
/opt/local/qt5/qtbase/mkspecs/features/lex.prf:
mt0.pro:
/opt/local/qt5/qtbase/lib/QtWidgets.framework/QtWidgets.prl:
/opt/local/qt5/qtbase/lib/QtGui.framework/QtGui.prl:
/opt/local/qt5/qtbase/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile mt0.pro

qmake_all: FORCE

mt0.app/Contents/PkgInfo: 
	@test -d mt0.app/Contents || mkdir -p mt0.app/Contents
	@$(DEL_FILE) mt0.app/Contents/PkgInfo
	@echo "APPL????" > mt0.app/Contents/PkgInfo
mt0.app/Contents/Resources/empty.lproj: 
	@test -d mt0.app/Contents/Resources || mkdir -p mt0.app/Contents/Resources
	@touch mt0.app/Contents/Resources/empty.lproj
	
mt0.app/Contents/Info.plist: 
	@test -d mt0.app/Contents || mkdir -p mt0.app/Contents
	@$(DEL_FILE) mt0.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,GeissbergStudios.mt0,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},GeissbergStudios.mt0,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,mt0,g" -e "s,@LIBRARY@,mt0,g" -e "s,\$${EXECUTABLE_NAME},mt0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" /opt/local/qt5/qtbase/mkspecs/macx-clang/Info.plist.app >mt0.app/Contents/Info.plist

all: Makefile \
		mt0.app/Contents/PkgInfo \
		mt0.app/Contents/Resources/empty.lproj \
		mt0.app/Contents/Info.plist mt0.app/Contents/MacOS/mt0

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/local/qt5/qtbase/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents dialog.hh driveHardware.hh $(DISTDIR)/
	$(COPY_FILE) --parents main.cc dialog.cc drivehardware.cc $(DISTDIR)/
	$(COPY_FILE) --parents dialog.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r mt0.app
	-$(DEL_FILE) /Users/ursl/pi/qt/mt0/uic_wrapper.sh /Users/ursl/pi/qt/mt0/uic_wrapper.sh .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)"

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/local/qt5/qtbase/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h /opt/local/qt5/qtbase/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_dialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_dialog.cpp
moc_dialog.cpp: dialog.hh \
		/opt/local/qt5/qtbase/include/QtWidgets/QDialog \
		/opt/local/qt5/qtbase/include/QtWidgets/qdialog.h \
		/opt/local/qt5/qtbase/src/widgets/dialogs/qdialog.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qtwidgetsglobal.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qtwidgetsglobal.h \
		/opt/local/qt5/qtbase/include/QtGui/qtguiglobal.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qtguiglobal.h \
		/opt/local/qt5/qtbase/include/QtCore/qglobal.h \
		/opt/local/qt5/qtbase/src/corelib/global/qglobal.h \
		/opt/local/qt5/qtbase/include/QtCore/qconfig-bootstrapped.h \
		/opt/local/qt5/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		/opt/local/qt5/qtbase/include/QtCore/qconfig.h \
		/opt/local/qt5/qtbase/src/corelib/global/qconfig.h \
		/opt/local/qt5/qtbase/include/QtCore/qtcore-config.h \
		/opt/local/qt5/qtbase/src/corelib/qtcore-config.h \
		/opt/local/qt5/qtbase/include/QtCore/qsystemdetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qsystemdetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qprocessordetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qprocessordetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qcompilerdetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qcompilerdetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qtypeinfo.h \
		/opt/local/qt5/qtbase/src/corelib/global/qtypeinfo.h \
		/opt/local/qt5/qtbase/include/QtCore/qsysinfo.h \
		/opt/local/qt5/qtbase/src/corelib/global/qsysinfo.h \
		/opt/local/qt5/qtbase/include/QtCore/qlogging.h \
		/opt/local/qt5/qtbase/src/corelib/global/qlogging.h \
		/opt/local/qt5/qtbase/include/QtCore/qflags.h \
		/opt/local/qt5/qtbase/src/corelib/global/qflags.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qbasicatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qbasicatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_bootstrap.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		/opt/local/qt5/qtbase/include/QtCore/qgenericatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qgenericatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_cxx11.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_cxx11.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_msvc.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_msvc.h \
		/opt/local/qt5/qtbase/include/QtCore/qglobalstatic.h \
		/opt/local/qt5/qtbase/src/corelib/global/qglobalstatic.h \
		/opt/local/qt5/qtbase/include/QtCore/qmutex.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qmutex.h \
		/opt/local/qt5/qtbase/include/QtCore/qnumeric.h \
		/opt/local/qt5/qtbase/src/corelib/global/qnumeric.h \
		/opt/local/qt5/qtbase/include/QtCore/qversiontagging.h \
		/opt/local/qt5/qtbase/src/corelib/global/qversiontagging.h \
		/opt/local/qt5/qtbase/include/QtGui/qtgui-config.h \
		/opt/local/qt5/qtbase/src/gui/qtgui-config.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qtwidgets-config.h \
		/opt/local/qt5/qtbase/src/widgets/qtwidgets-config.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qwidget.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qwidget.h \
		/opt/local/qt5/qtbase/include/QtGui/qwindowdefs.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qwindowdefs.h \
		/opt/local/qt5/qtbase/include/QtCore/qobjectdefs.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobjectdefs.h \
		/opt/local/qt5/qtbase/include/QtCore/qnamespace.h \
		/opt/local/qt5/qtbase/src/corelib/global/qnamespace.h \
		/opt/local/qt5/qtbase/include/QtCore/qobjectdefs_impl.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		/opt/local/qt5/qtbase/include/QtGui/qwindowdefs_win.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qwindowdefs_win.h \
		/opt/local/qt5/qtbase/include/QtCore/qobject.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobject.h \
		/opt/local/qt5/qtbase/include/QtCore/qstring.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstring.h \
		/opt/local/qt5/qtbase/include/QtCore/qchar.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qchar.h \
		/opt/local/qt5/qtbase/include/QtCore/qbytearray.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qbytearray.h \
		/opt/local/qt5/qtbase/include/QtCore/qrefcount.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qrefcount.h \
		/opt/local/qt5/qtbase/include/QtCore/qarraydata.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qarraydata.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringliteral.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringliteral.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringalgorithms.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringalgorithms.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringview.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringview.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringbuilder.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringbuilder.h \
		/opt/local/qt5/qtbase/include/QtCore/qlist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qlist.h \
		/opt/local/qt5/qtbase/include/QtCore/qalgorithms.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qalgorithms.h \
		/opt/local/qt5/qtbase/include/QtCore/qiterator.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qiterator.h \
		/opt/local/qt5/qtbase/include/QtCore/qhashfunctions.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qhashfunctions.h \
		/opt/local/qt5/qtbase/include/QtCore/qpair.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qpair.h \
		/opt/local/qt5/qtbase/include/QtCore/qbytearraylist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qbytearraylist.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringlist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringlist.h \
		/opt/local/qt5/qtbase/include/QtCore/qregexp.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qregexp.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringmatcher.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringmatcher.h \
		/opt/local/qt5/qtbase/include/QtCore/qcoreevent.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qcoreevent.h \
		/opt/local/qt5/qtbase/include/QtCore/qscopedpointer.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qscopedpointer.h \
		/opt/local/qt5/qtbase/include/QtCore/qmetatype.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qmetatype.h \
		/opt/local/qt5/qtbase/include/QtCore/qvarlengtharray.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qvarlengtharray.h \
		/opt/local/qt5/qtbase/include/QtCore/qcontainerfwd.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qcontainerfwd.h \
		/opt/local/qt5/qtbase/include/QtCore/qobject_impl.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobject_impl.h \
		/opt/local/qt5/qtbase/include/QtCore/qmargins.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qmargins.h \
		/opt/local/qt5/qtbase/include/QtGui/qpaintdevice.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpaintdevice.h \
		/opt/local/qt5/qtbase/include/QtCore/qrect.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qrect.h \
		/opt/local/qt5/qtbase/include/QtCore/qsize.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsize.h \
		/opt/local/qt5/qtbase/include/QtCore/qpoint.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qpoint.h \
		/opt/local/qt5/qtbase/include/QtGui/qpalette.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qpalette.h \
		/opt/local/qt5/qtbase/include/QtGui/qcolor.h \
		/opt/local/qt5/qtbase/src/gui/painting/qcolor.h \
		/opt/local/qt5/qtbase/include/QtGui/qrgb.h \
		/opt/local/qt5/qtbase/src/gui/painting/qrgb.h \
		/opt/local/qt5/qtbase/include/QtGui/qrgba64.h \
		/opt/local/qt5/qtbase/src/gui/painting/qrgba64.h \
		/opt/local/qt5/qtbase/include/QtGui/qbrush.h \
		/opt/local/qt5/qtbase/src/gui/painting/qbrush.h \
		/opt/local/qt5/qtbase/include/QtCore/qvector.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qvector.h \
		/opt/local/qt5/qtbase/include/QtGui/qmatrix.h \
		/opt/local/qt5/qtbase/src/gui/painting/qmatrix.h \
		/opt/local/qt5/qtbase/include/QtGui/qpolygon.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpolygon.h \
		/opt/local/qt5/qtbase/include/QtGui/qregion.h \
		/opt/local/qt5/qtbase/src/gui/painting/qregion.h \
		/opt/local/qt5/qtbase/include/QtCore/qdatastream.h \
		/opt/local/qt5/qtbase/src/corelib/serialization/qdatastream.h \
		/opt/local/qt5/qtbase/include/QtCore/qiodevice.h \
		/opt/local/qt5/qtbase/src/corelib/io/qiodevice.h \
		/opt/local/qt5/qtbase/include/QtCore/qline.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qline.h \
		/opt/local/qt5/qtbase/include/QtGui/qtransform.h \
		/opt/local/qt5/qtbase/src/gui/painting/qtransform.h \
		/opt/local/qt5/qtbase/include/QtGui/qpainterpath.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpainterpath.h \
		/opt/local/qt5/qtbase/include/QtGui/qimage.h \
		/opt/local/qt5/qtbase/src/gui/image/qimage.h \
		/opt/local/qt5/qtbase/include/QtGui/qpixelformat.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qpixelformat.h \
		/opt/local/qt5/qtbase/include/QtGui/qpixmap.h \
		/opt/local/qt5/qtbase/src/gui/image/qpixmap.h \
		/opt/local/qt5/qtbase/include/QtCore/qsharedpointer.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsharedpointer.h \
		/opt/local/qt5/qtbase/include/QtCore/qshareddata.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qshareddata.h \
		/opt/local/qt5/qtbase/include/QtCore/qhash.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qhash.h \
		/opt/local/qt5/qtbase/include/QtCore/qsharedpointer_impl.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		/opt/local/qt5/qtbase/include/QtGui/qfont.h \
		/opt/local/qt5/qtbase/src/gui/text/qfont.h \
		/opt/local/qt5/qtbase/include/QtGui/qfontmetrics.h \
		/opt/local/qt5/qtbase/src/gui/text/qfontmetrics.h \
		/opt/local/qt5/qtbase/include/QtGui/qfontinfo.h \
		/opt/local/qt5/qtbase/src/gui/text/qfontinfo.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qsizepolicy.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qsizepolicy.h \
		/opt/local/qt5/qtbase/include/QtGui/qcursor.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qcursor.h \
		/opt/local/qt5/qtbase/include/QtGui/qkeysequence.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qkeysequence.h \
		/opt/local/qt5/qtbase/include/QtGui/qevent.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qevent.h \
		/opt/local/qt5/qtbase/include/QtCore/qvariant.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qvariant.h \
		/opt/local/qt5/qtbase/include/QtCore/qmap.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qmap.h \
		/opt/local/qt5/qtbase/include/QtCore/qdebug.h \
		/opt/local/qt5/qtbase/src/corelib/io/qdebug.h \
		/opt/local/qt5/qtbase/include/QtCore/qtextstream.h \
		/opt/local/qt5/qtbase/src/corelib/serialization/qtextstream.h \
		/opt/local/qt5/qtbase/include/QtCore/qlocale.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qlocale.h \
		/opt/local/qt5/qtbase/include/QtCore/qset.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qset.h \
		/opt/local/qt5/qtbase/include/QtCore/qcontiguouscache.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qcontiguouscache.h \
		/opt/local/qt5/qtbase/include/QtCore/qurl.h \
		/opt/local/qt5/qtbase/src/corelib/io/qurl.h \
		/opt/local/qt5/qtbase/include/QtCore/qurlquery.h \
		/opt/local/qt5/qtbase/src/corelib/io/qurlquery.h \
		/opt/local/qt5/qtbase/include/QtCore/qfile.h \
		/opt/local/qt5/qtbase/src/corelib/io/qfile.h \
		/opt/local/qt5/qtbase/include/QtCore/qfiledevice.h \
		/opt/local/qt5/qtbase/src/corelib/io/qfiledevice.h \
		/opt/local/qt5/qtbase/include/QtGui/qvector2d.h \
		/opt/local/qt5/qtbase/src/gui/math3d/qvector2d.h \
		/opt/local/qt5/qtbase/include/QtGui/qtouchdevice.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qtouchdevice.h \
		moc_predefs.h \
		/opt/local/qt5/qtbase/bin/moc
	/opt/local/qt5/qtbase/bin/moc $(DEFINES) --include /Users/ursl/pi/qt/mt0/moc_predefs.h -I/opt/local/qt5/qtbase/mkspecs/macx-clang -I/Users/ursl/pi/qt/mt0 -I/Users/ursl/pi/qt/mt0 -I/opt/local/qt5/qtbase/include -I/opt/local/qt5/qtbase/include/QtWidgets -I/opt/local/qt5/qtbase/include/QtGui -I/opt/local/qt5/qtbase/include/QtCore -I/usr/local/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include/c++/v1 -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/11.0.3/include -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -F/opt/local/qt5/qtbase/lib dialog.hh -o moc_dialog.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_dialog.h
compiler_uic_clean:
	-$(DEL_FILE) ui_dialog.h
ui_dialog.h: dialog.ui \
		/opt/local/qt5/qtbase/bin/uic
	/Users/ursl/pi/qt/mt0/uic_wrapper.sh dialog.ui -o ui_dialog.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cc /opt/local/qt5/qtbase/include/QtWidgets/QApplication \
		/opt/local/qt5/qtbase/include/QtWidgets/qapplication.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qapplication.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qtwidgetsglobal.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qtwidgetsglobal.h \
		/opt/local/qt5/qtbase/include/QtGui/qtguiglobal.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qtguiglobal.h \
		/opt/local/qt5/qtbase/include/QtCore/qglobal.h \
		/opt/local/qt5/qtbase/src/corelib/global/qglobal.h \
		/opt/local/qt5/qtbase/include/QtCore/qconfig-bootstrapped.h \
		/opt/local/qt5/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		/opt/local/qt5/qtbase/include/QtCore/qconfig.h \
		/opt/local/qt5/qtbase/src/corelib/global/qconfig.h \
		/opt/local/qt5/qtbase/include/QtCore/qtcore-config.h \
		/opt/local/qt5/qtbase/src/corelib/qtcore-config.h \
		/opt/local/qt5/qtbase/include/QtCore/qsystemdetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qsystemdetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qprocessordetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qprocessordetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qcompilerdetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qcompilerdetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qtypeinfo.h \
		/opt/local/qt5/qtbase/src/corelib/global/qtypeinfo.h \
		/opt/local/qt5/qtbase/include/QtCore/qsysinfo.h \
		/opt/local/qt5/qtbase/src/corelib/global/qsysinfo.h \
		/opt/local/qt5/qtbase/include/QtCore/qlogging.h \
		/opt/local/qt5/qtbase/src/corelib/global/qlogging.h \
		/opt/local/qt5/qtbase/include/QtCore/qflags.h \
		/opt/local/qt5/qtbase/src/corelib/global/qflags.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qbasicatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qbasicatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_bootstrap.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		/opt/local/qt5/qtbase/include/QtCore/qgenericatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qgenericatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_cxx11.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_cxx11.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_msvc.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_msvc.h \
		/opt/local/qt5/qtbase/include/QtCore/qglobalstatic.h \
		/opt/local/qt5/qtbase/src/corelib/global/qglobalstatic.h \
		/opt/local/qt5/qtbase/include/QtCore/qmutex.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qmutex.h \
		/opt/local/qt5/qtbase/include/QtCore/qnumeric.h \
		/opt/local/qt5/qtbase/src/corelib/global/qnumeric.h \
		/opt/local/qt5/qtbase/include/QtCore/qversiontagging.h \
		/opt/local/qt5/qtbase/src/corelib/global/qversiontagging.h \
		/opt/local/qt5/qtbase/include/QtGui/qtgui-config.h \
		/opt/local/qt5/qtbase/src/gui/qtgui-config.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qtwidgets-config.h \
		/opt/local/qt5/qtbase/src/widgets/qtwidgets-config.h \
		/opt/local/qt5/qtbase/include/QtCore/qcoreapplication.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qcoreapplication.h \
		/opt/local/qt5/qtbase/include/QtCore/qstring.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstring.h \
		/opt/local/qt5/qtbase/include/QtCore/qchar.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qchar.h \
		/opt/local/qt5/qtbase/include/QtCore/qbytearray.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qbytearray.h \
		/opt/local/qt5/qtbase/include/QtCore/qrefcount.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qrefcount.h \
		/opt/local/qt5/qtbase/include/QtCore/qnamespace.h \
		/opt/local/qt5/qtbase/src/corelib/global/qnamespace.h \
		/opt/local/qt5/qtbase/include/QtCore/qarraydata.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qarraydata.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringliteral.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringliteral.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringalgorithms.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringalgorithms.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringview.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringview.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringbuilder.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringbuilder.h \
		/opt/local/qt5/qtbase/include/QtCore/qobject.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobject.h \
		/opt/local/qt5/qtbase/include/QtCore/qobjectdefs.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobjectdefs.h \
		/opt/local/qt5/qtbase/include/QtCore/qobjectdefs_impl.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		/opt/local/qt5/qtbase/include/QtCore/qlist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qlist.h \
		/opt/local/qt5/qtbase/include/QtCore/qalgorithms.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qalgorithms.h \
		/opt/local/qt5/qtbase/include/QtCore/qiterator.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qiterator.h \
		/opt/local/qt5/qtbase/include/QtCore/qhashfunctions.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qhashfunctions.h \
		/opt/local/qt5/qtbase/include/QtCore/qpair.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qpair.h \
		/opt/local/qt5/qtbase/include/QtCore/qbytearraylist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qbytearraylist.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringlist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringlist.h \
		/opt/local/qt5/qtbase/include/QtCore/qregexp.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qregexp.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringmatcher.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringmatcher.h \
		/opt/local/qt5/qtbase/include/QtCore/qcoreevent.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qcoreevent.h \
		/opt/local/qt5/qtbase/include/QtCore/qscopedpointer.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qscopedpointer.h \
		/opt/local/qt5/qtbase/include/QtCore/qmetatype.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qmetatype.h \
		/opt/local/qt5/qtbase/include/QtCore/qvarlengtharray.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qvarlengtharray.h \
		/opt/local/qt5/qtbase/include/QtCore/qcontainerfwd.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qcontainerfwd.h \
		/opt/local/qt5/qtbase/include/QtCore/qobject_impl.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobject_impl.h \
		/opt/local/qt5/qtbase/include/QtCore/qeventloop.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qeventloop.h \
		/opt/local/qt5/qtbase/include/QtGui/qwindowdefs.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qwindowdefs.h \
		/opt/local/qt5/qtbase/include/QtGui/qwindowdefs_win.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qwindowdefs_win.h \
		/opt/local/qt5/qtbase/include/QtCore/qpoint.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qpoint.h \
		/opt/local/qt5/qtbase/include/QtCore/qsize.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsize.h \
		/opt/local/qt5/qtbase/include/QtGui/qcursor.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qcursor.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qdesktopwidget.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qdesktopwidget.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qwidget.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qwidget.h \
		/opt/local/qt5/qtbase/include/QtCore/qmargins.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qmargins.h \
		/opt/local/qt5/qtbase/include/QtGui/qpaintdevice.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpaintdevice.h \
		/opt/local/qt5/qtbase/include/QtCore/qrect.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qrect.h \
		/opt/local/qt5/qtbase/include/QtGui/qpalette.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qpalette.h \
		/opt/local/qt5/qtbase/include/QtGui/qcolor.h \
		/opt/local/qt5/qtbase/src/gui/painting/qcolor.h \
		/opt/local/qt5/qtbase/include/QtGui/qrgb.h \
		/opt/local/qt5/qtbase/src/gui/painting/qrgb.h \
		/opt/local/qt5/qtbase/include/QtGui/qrgba64.h \
		/opt/local/qt5/qtbase/src/gui/painting/qrgba64.h \
		/opt/local/qt5/qtbase/include/QtGui/qbrush.h \
		/opt/local/qt5/qtbase/src/gui/painting/qbrush.h \
		/opt/local/qt5/qtbase/include/QtCore/qvector.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qvector.h \
		/opt/local/qt5/qtbase/include/QtGui/qmatrix.h \
		/opt/local/qt5/qtbase/src/gui/painting/qmatrix.h \
		/opt/local/qt5/qtbase/include/QtGui/qpolygon.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpolygon.h \
		/opt/local/qt5/qtbase/include/QtGui/qregion.h \
		/opt/local/qt5/qtbase/src/gui/painting/qregion.h \
		/opt/local/qt5/qtbase/include/QtCore/qdatastream.h \
		/opt/local/qt5/qtbase/src/corelib/serialization/qdatastream.h \
		/opt/local/qt5/qtbase/include/QtCore/qiodevice.h \
		/opt/local/qt5/qtbase/src/corelib/io/qiodevice.h \
		/opt/local/qt5/qtbase/include/QtCore/qline.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qline.h \
		/opt/local/qt5/qtbase/include/QtGui/qtransform.h \
		/opt/local/qt5/qtbase/src/gui/painting/qtransform.h \
		/opt/local/qt5/qtbase/include/QtGui/qpainterpath.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpainterpath.h \
		/opt/local/qt5/qtbase/include/QtGui/qimage.h \
		/opt/local/qt5/qtbase/src/gui/image/qimage.h \
		/opt/local/qt5/qtbase/include/QtGui/qpixelformat.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qpixelformat.h \
		/opt/local/qt5/qtbase/include/QtGui/qpixmap.h \
		/opt/local/qt5/qtbase/src/gui/image/qpixmap.h \
		/opt/local/qt5/qtbase/include/QtCore/qsharedpointer.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsharedpointer.h \
		/opt/local/qt5/qtbase/include/QtCore/qshareddata.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qshareddata.h \
		/opt/local/qt5/qtbase/include/QtCore/qhash.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qhash.h \
		/opt/local/qt5/qtbase/include/QtCore/qsharedpointer_impl.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		/opt/local/qt5/qtbase/include/QtGui/qfont.h \
		/opt/local/qt5/qtbase/src/gui/text/qfont.h \
		/opt/local/qt5/qtbase/include/QtGui/qfontmetrics.h \
		/opt/local/qt5/qtbase/src/gui/text/qfontmetrics.h \
		/opt/local/qt5/qtbase/include/QtGui/qfontinfo.h \
		/opt/local/qt5/qtbase/src/gui/text/qfontinfo.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qsizepolicy.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qsizepolicy.h \
		/opt/local/qt5/qtbase/include/QtGui/qkeysequence.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qkeysequence.h \
		/opt/local/qt5/qtbase/include/QtGui/qevent.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qevent.h \
		/opt/local/qt5/qtbase/include/QtCore/qvariant.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qvariant.h \
		/opt/local/qt5/qtbase/include/QtCore/qmap.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qmap.h \
		/opt/local/qt5/qtbase/include/QtCore/qdebug.h \
		/opt/local/qt5/qtbase/src/corelib/io/qdebug.h \
		/opt/local/qt5/qtbase/include/QtCore/qtextstream.h \
		/opt/local/qt5/qtbase/src/corelib/serialization/qtextstream.h \
		/opt/local/qt5/qtbase/include/QtCore/qlocale.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qlocale.h \
		/opt/local/qt5/qtbase/include/QtCore/qset.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qset.h \
		/opt/local/qt5/qtbase/include/QtCore/qcontiguouscache.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qcontiguouscache.h \
		/opt/local/qt5/qtbase/include/QtCore/qurl.h \
		/opt/local/qt5/qtbase/src/corelib/io/qurl.h \
		/opt/local/qt5/qtbase/include/QtCore/qurlquery.h \
		/opt/local/qt5/qtbase/src/corelib/io/qurlquery.h \
		/opt/local/qt5/qtbase/include/QtCore/qfile.h \
		/opt/local/qt5/qtbase/src/corelib/io/qfile.h \
		/opt/local/qt5/qtbase/include/QtCore/qfiledevice.h \
		/opt/local/qt5/qtbase/src/corelib/io/qfiledevice.h \
		/opt/local/qt5/qtbase/include/QtGui/qvector2d.h \
		/opt/local/qt5/qtbase/src/gui/math3d/qvector2d.h \
		/opt/local/qt5/qtbase/include/QtGui/qtouchdevice.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qtouchdevice.h \
		/opt/local/qt5/qtbase/include/QtGui/qguiapplication.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qguiapplication.h \
		/opt/local/qt5/qtbase/include/QtGui/qinputmethod.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qinputmethod.h \
		/opt/local/qt5/qtbase/include/QtWidgets/QPushButton \
		/opt/local/qt5/qtbase/include/QtWidgets/qpushbutton.h \
		/opt/local/qt5/qtbase/src/widgets/widgets/qpushbutton.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qabstractbutton.h \
		/opt/local/qt5/qtbase/src/widgets/widgets/qabstractbutton.h \
		/opt/local/qt5/qtbase/include/QtGui/qicon.h \
		/opt/local/qt5/qtbase/src/gui/image/qicon.h \
		/opt/local/qt5/qtbase/include/QtCore/QThread \
		/opt/local/qt5/qtbase/include/QtCore/qthread.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qthread.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cc

dialog.o: dialog.cc dialog.hh \
		/opt/local/qt5/qtbase/include/QtWidgets/QDialog \
		/opt/local/qt5/qtbase/include/QtWidgets/qdialog.h \
		/opt/local/qt5/qtbase/src/widgets/dialogs/qdialog.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qtwidgetsglobal.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qtwidgetsglobal.h \
		/opt/local/qt5/qtbase/include/QtGui/qtguiglobal.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qtguiglobal.h \
		/opt/local/qt5/qtbase/include/QtCore/qglobal.h \
		/opt/local/qt5/qtbase/src/corelib/global/qglobal.h \
		/opt/local/qt5/qtbase/include/QtCore/qconfig-bootstrapped.h \
		/opt/local/qt5/qtbase/src/corelib/global/qconfig-bootstrapped.h \
		/opt/local/qt5/qtbase/include/QtCore/qconfig.h \
		/opt/local/qt5/qtbase/src/corelib/global/qconfig.h \
		/opt/local/qt5/qtbase/include/QtCore/qtcore-config.h \
		/opt/local/qt5/qtbase/src/corelib/qtcore-config.h \
		/opt/local/qt5/qtbase/include/QtCore/qsystemdetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qsystemdetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qprocessordetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qprocessordetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qcompilerdetection.h \
		/opt/local/qt5/qtbase/src/corelib/global/qcompilerdetection.h \
		/opt/local/qt5/qtbase/include/QtCore/qtypeinfo.h \
		/opt/local/qt5/qtbase/src/corelib/global/qtypeinfo.h \
		/opt/local/qt5/qtbase/include/QtCore/qsysinfo.h \
		/opt/local/qt5/qtbase/src/corelib/global/qsysinfo.h \
		/opt/local/qt5/qtbase/include/QtCore/qlogging.h \
		/opt/local/qt5/qtbase/src/corelib/global/qlogging.h \
		/opt/local/qt5/qtbase/include/QtCore/qflags.h \
		/opt/local/qt5/qtbase/src/corelib/global/qflags.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qbasicatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qbasicatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_bootstrap.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_bootstrap.h \
		/opt/local/qt5/qtbase/include/QtCore/qgenericatomic.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qgenericatomic.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_cxx11.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_cxx11.h \
		/opt/local/qt5/qtbase/include/QtCore/qatomic_msvc.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qatomic_msvc.h \
		/opt/local/qt5/qtbase/include/QtCore/qglobalstatic.h \
		/opt/local/qt5/qtbase/src/corelib/global/qglobalstatic.h \
		/opt/local/qt5/qtbase/include/QtCore/qmutex.h \
		/opt/local/qt5/qtbase/src/corelib/thread/qmutex.h \
		/opt/local/qt5/qtbase/include/QtCore/qnumeric.h \
		/opt/local/qt5/qtbase/src/corelib/global/qnumeric.h \
		/opt/local/qt5/qtbase/include/QtCore/qversiontagging.h \
		/opt/local/qt5/qtbase/src/corelib/global/qversiontagging.h \
		/opt/local/qt5/qtbase/include/QtGui/qtgui-config.h \
		/opt/local/qt5/qtbase/src/gui/qtgui-config.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qtwidgets-config.h \
		/opt/local/qt5/qtbase/src/widgets/qtwidgets-config.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qwidget.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qwidget.h \
		/opt/local/qt5/qtbase/include/QtGui/qwindowdefs.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qwindowdefs.h \
		/opt/local/qt5/qtbase/include/QtCore/qobjectdefs.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobjectdefs.h \
		/opt/local/qt5/qtbase/include/QtCore/qnamespace.h \
		/opt/local/qt5/qtbase/src/corelib/global/qnamespace.h \
		/opt/local/qt5/qtbase/include/QtCore/qobjectdefs_impl.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobjectdefs_impl.h \
		/opt/local/qt5/qtbase/include/QtGui/qwindowdefs_win.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qwindowdefs_win.h \
		/opt/local/qt5/qtbase/include/QtCore/qobject.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobject.h \
		/opt/local/qt5/qtbase/include/QtCore/qstring.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstring.h \
		/opt/local/qt5/qtbase/include/QtCore/qchar.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qchar.h \
		/opt/local/qt5/qtbase/include/QtCore/qbytearray.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qbytearray.h \
		/opt/local/qt5/qtbase/include/QtCore/qrefcount.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qrefcount.h \
		/opt/local/qt5/qtbase/include/QtCore/qarraydata.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qarraydata.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringliteral.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringliteral.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringalgorithms.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringalgorithms.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringview.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringview.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringbuilder.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringbuilder.h \
		/opt/local/qt5/qtbase/include/QtCore/qlist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qlist.h \
		/opt/local/qt5/qtbase/include/QtCore/qalgorithms.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qalgorithms.h \
		/opt/local/qt5/qtbase/include/QtCore/qiterator.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qiterator.h \
		/opt/local/qt5/qtbase/include/QtCore/qhashfunctions.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qhashfunctions.h \
		/opt/local/qt5/qtbase/include/QtCore/qpair.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qpair.h \
		/opt/local/qt5/qtbase/include/QtCore/qbytearraylist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qbytearraylist.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringlist.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringlist.h \
		/opt/local/qt5/qtbase/include/QtCore/qregexp.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qregexp.h \
		/opt/local/qt5/qtbase/include/QtCore/qstringmatcher.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qstringmatcher.h \
		/opt/local/qt5/qtbase/include/QtCore/qcoreevent.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qcoreevent.h \
		/opt/local/qt5/qtbase/include/QtCore/qscopedpointer.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qscopedpointer.h \
		/opt/local/qt5/qtbase/include/QtCore/qmetatype.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qmetatype.h \
		/opt/local/qt5/qtbase/include/QtCore/qvarlengtharray.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qvarlengtharray.h \
		/opt/local/qt5/qtbase/include/QtCore/qcontainerfwd.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qcontainerfwd.h \
		/opt/local/qt5/qtbase/include/QtCore/qobject_impl.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qobject_impl.h \
		/opt/local/qt5/qtbase/include/QtCore/qmargins.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qmargins.h \
		/opt/local/qt5/qtbase/include/QtGui/qpaintdevice.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpaintdevice.h \
		/opt/local/qt5/qtbase/include/QtCore/qrect.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qrect.h \
		/opt/local/qt5/qtbase/include/QtCore/qsize.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsize.h \
		/opt/local/qt5/qtbase/include/QtCore/qpoint.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qpoint.h \
		/opt/local/qt5/qtbase/include/QtGui/qpalette.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qpalette.h \
		/opt/local/qt5/qtbase/include/QtGui/qcolor.h \
		/opt/local/qt5/qtbase/src/gui/painting/qcolor.h \
		/opt/local/qt5/qtbase/include/QtGui/qrgb.h \
		/opt/local/qt5/qtbase/src/gui/painting/qrgb.h \
		/opt/local/qt5/qtbase/include/QtGui/qrgba64.h \
		/opt/local/qt5/qtbase/src/gui/painting/qrgba64.h \
		/opt/local/qt5/qtbase/include/QtGui/qbrush.h \
		/opt/local/qt5/qtbase/src/gui/painting/qbrush.h \
		/opt/local/qt5/qtbase/include/QtCore/qvector.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qvector.h \
		/opt/local/qt5/qtbase/include/QtGui/qmatrix.h \
		/opt/local/qt5/qtbase/src/gui/painting/qmatrix.h \
		/opt/local/qt5/qtbase/include/QtGui/qpolygon.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpolygon.h \
		/opt/local/qt5/qtbase/include/QtGui/qregion.h \
		/opt/local/qt5/qtbase/src/gui/painting/qregion.h \
		/opt/local/qt5/qtbase/include/QtCore/qdatastream.h \
		/opt/local/qt5/qtbase/src/corelib/serialization/qdatastream.h \
		/opt/local/qt5/qtbase/include/QtCore/qiodevice.h \
		/opt/local/qt5/qtbase/src/corelib/io/qiodevice.h \
		/opt/local/qt5/qtbase/include/QtCore/qline.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qline.h \
		/opt/local/qt5/qtbase/include/QtGui/qtransform.h \
		/opt/local/qt5/qtbase/src/gui/painting/qtransform.h \
		/opt/local/qt5/qtbase/include/QtGui/qpainterpath.h \
		/opt/local/qt5/qtbase/src/gui/painting/qpainterpath.h \
		/opt/local/qt5/qtbase/include/QtGui/qimage.h \
		/opt/local/qt5/qtbase/src/gui/image/qimage.h \
		/opt/local/qt5/qtbase/include/QtGui/qpixelformat.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qpixelformat.h \
		/opt/local/qt5/qtbase/include/QtGui/qpixmap.h \
		/opt/local/qt5/qtbase/src/gui/image/qpixmap.h \
		/opt/local/qt5/qtbase/include/QtCore/qsharedpointer.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsharedpointer.h \
		/opt/local/qt5/qtbase/include/QtCore/qshareddata.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qshareddata.h \
		/opt/local/qt5/qtbase/include/QtCore/qhash.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qhash.h \
		/opt/local/qt5/qtbase/include/QtCore/qsharedpointer_impl.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qsharedpointer_impl.h \
		/opt/local/qt5/qtbase/include/QtGui/qfont.h \
		/opt/local/qt5/qtbase/src/gui/text/qfont.h \
		/opt/local/qt5/qtbase/include/QtGui/qfontmetrics.h \
		/opt/local/qt5/qtbase/src/gui/text/qfontmetrics.h \
		/opt/local/qt5/qtbase/include/QtGui/qfontinfo.h \
		/opt/local/qt5/qtbase/src/gui/text/qfontinfo.h \
		/opt/local/qt5/qtbase/include/QtWidgets/qsizepolicy.h \
		/opt/local/qt5/qtbase/src/widgets/kernel/qsizepolicy.h \
		/opt/local/qt5/qtbase/include/QtGui/qcursor.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qcursor.h \
		/opt/local/qt5/qtbase/include/QtGui/qkeysequence.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qkeysequence.h \
		/opt/local/qt5/qtbase/include/QtGui/qevent.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qevent.h \
		/opt/local/qt5/qtbase/include/QtCore/qvariant.h \
		/opt/local/qt5/qtbase/src/corelib/kernel/qvariant.h \
		/opt/local/qt5/qtbase/include/QtCore/qmap.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qmap.h \
		/opt/local/qt5/qtbase/include/QtCore/qdebug.h \
		/opt/local/qt5/qtbase/src/corelib/io/qdebug.h \
		/opt/local/qt5/qtbase/include/QtCore/qtextstream.h \
		/opt/local/qt5/qtbase/src/corelib/serialization/qtextstream.h \
		/opt/local/qt5/qtbase/include/QtCore/qlocale.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qlocale.h \
		/opt/local/qt5/qtbase/include/QtCore/qset.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qset.h \
		/opt/local/qt5/qtbase/include/QtCore/qcontiguouscache.h \
		/opt/local/qt5/qtbase/src/corelib/tools/qcontiguouscache.h \
		/opt/local/qt5/qtbase/include/QtCore/qurl.h \
		/opt/local/qt5/qtbase/src/corelib/io/qurl.h \
		/opt/local/qt5/qtbase/include/QtCore/qurlquery.h \
		/opt/local/qt5/qtbase/src/corelib/io/qurlquery.h \
		/opt/local/qt5/qtbase/include/QtCore/qfile.h \
		/opt/local/qt5/qtbase/src/corelib/io/qfile.h \
		/opt/local/qt5/qtbase/include/QtCore/qfiledevice.h \
		/opt/local/qt5/qtbase/src/corelib/io/qfiledevice.h \
		/opt/local/qt5/qtbase/include/QtGui/qvector2d.h \
		/opt/local/qt5/qtbase/src/gui/math3d/qvector2d.h \
		/opt/local/qt5/qtbase/include/QtGui/qtouchdevice.h \
		/opt/local/qt5/qtbase/src/gui/kernel/qtouchdevice.h \
		ui_dialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dialog.o dialog.cc

drivehardware.o: drivehardware.cc driveHardware.hh
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o drivehardware.o drivehardware.cc

moc_dialog.o: moc_dialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dialog.o moc_dialog.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

