/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trpc.h"

#include <stdlib.h>
#include <stdio.h>
#include <string.h>

void
trpc_6(char *host, char *cmd, float argtemp)
{
	CLIENT *clnt;
	void  *result_1;
	args  settemp_6_arg;
	float  *result_2;
	char *gettemp_6_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TRPC, TRPC_VERS, "udp");
        printf("Hallo in DEBUG\n");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	if (!strcmp("settemp", cmd)) {
	  settemp_6_arg.value = argtemp;
	  printf("calling from trpc_6 with settemp_6_arg.value = %f\n", settemp_6_arg.value);
	  result_1 = settemp_6(&settemp_6_arg, clnt);
	  if (result_1 == (void *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	}
	if (!strcmp("gettemp", cmd)) {
	  result_2 = gettemp_6((void*)&gettemp_6_arg, clnt);
	  printf("calling from trpc_6, returned temperature = %f\n", *result_2);
	  if (result_2 == (float *) NULL) {
	    clnt_perror (clnt, "call failed");
	  }
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
        char *host, *cmd;
	float temp;
	temp = 0.;

	if (argc < 2) {
		printf ("usage: %s server_host cmd [temperature]\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	cmd = argv[2];
	if (!strcmp("settemp", cmd)) {
	  temp = atoi(argv[3]);
	}
	trpc_6 (host, cmd, temp);
exit (0);
}
