/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct args {
	float value;
	char operation;
};
typedef struct args args;
#ifdef __cplusplus
extern "C" bool_t xdr_args(XDR *, args*);
#elif __STDC__
extern  bool_t xdr_args(XDR *, args*);
#else /* Old Style C */
bool_t xdr_args();
#endif /* Old Style C */


#define TRPC ((rpc_uint)456123789)
#define TRPC_VERS ((rpc_uint)6)

#ifdef __cplusplus
#define GOTEMP ((rpc_uint)1)
extern "C" float * gotemp_6(args *, CLIENT *);
extern "C" float * gotemp_6_svc(args *, struct svc_req *);
#define GOHUMI ((rpc_uint)2)
extern "C" float * gohumi_6(args *, CLIENT *);
extern "C" float * gohumi_6_svc(args *, struct svc_req *);

#elif __STDC__
#define GOTEMP ((rpc_uint)1)
extern  float * gotemp_6(args *, CLIENT *);
extern  float * gotemp_6_svc(args *, struct svc_req *);
#define GOHUMI ((rpc_uint)2)
extern  float * gohumi_6(args *, CLIENT *);
extern  float * gohumi_6_svc(args *, struct svc_req *);

#else /* Old Style C */
#define GOTEMP ((rpc_uint)1)
extern  float * gotemp_6();
extern  float * gotemp_6_svc();
#define GOHUMI ((rpc_uint)2)
extern  float * gohumi_6();
extern  float * gohumi_6_svc();
#endif /* Old Style C */

#endif /* !_IDL_H_RPCGEN */
