/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _IDL_H_RPCGEN
#define _IDL_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct args {
	float value;
	char operation;
};
typedef struct args args;

#define TRPC 456123789
#define TRPC_VERS 6

#if defined(__STDC__) || defined(__cplusplus)
#define GOTEMP 1
extern  float * gotemp_6(args *, CLIENT *);
extern  float * gotemp_6_svc(args *, struct svc_req *);
#define GOHUMI 2
extern  float * gohumi_6(args *, CLIENT *);
extern  float * gohumi_6_svc(args *, struct svc_req *);
extern int trpc_6_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GOTEMP 1
extern  float * gotemp_6();
extern  float * gotemp_6_svc();
#define GOHUMI 2
extern  float * gohumi_6();
extern  float * gohumi_6_svc();
extern int trpc_6_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_args (XDR *, args*);

#else /* K&R C */
extern bool_t xdr_args ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_IDL_H_RPCGEN */
