/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "IDL.h"

bool_t
xdr_args(XDR *xdrs, args *objp)
{

	if (!xdr_float(xdrs, &objp->value))
		return (FALSE);
	if (!xdr_char(xdrs, &objp->operation))
		return (FALSE);
	return (TRUE);
}
