/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"
#include <stdio.h>
#include <iostream>

float *
gotemp_6_svc(args *argp, struct svc_req *rqstp)
{

	static float  result;

	float t = argp->value;

	std::cout << "gotemp_6_svc to T = " <<  t << std::endl;

	return(&result);
}

float *
gohumi_6_svc(args *argp, struct svc_req *rqstp)
{

	static float  result;

	float t = argp->value;

	std::cout << "gohumi_6_svc to RH = " <<  t << std::endl;

	return(&result);
}
