/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "IDL.h"


void
trpc_6(char *host)
{
	CLIENT *clnt;
	float  *result_1;
	args  gotemp_6_arg;
	float  *result_2;
	args  gohumi_6_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, TRPC, TRPC_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = gotemp_6(&gotemp_6_arg, clnt);
	if (result_1 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	result_2 = gohumi_6(&gohumi_6_arg, clnt);
	if (result_2 == (float *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	trpc_6 (host);
exit (0);
}
