/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "trpc.h"

void *
settemp_6_svc(args *argp, struct svc_req *rqstp)
{
	static char * result;

	/*
	 * insert server code here
	 */

	return (void *) &result;
}

float *
gettemp_6_svc(void *argp, struct svc_req *rqstp)
{
	static float  result;

	/*
	 * insert server code here
	 */

	return &result;
}
